
from agents import(
    Agent, 
)
from pydantic import BaseModel

class Context_Request(BaseModel):
    is_query_valid_or_related_to_context: bool
    reasoning: str
    answer: str



guardrail_agent = Agent(
    name="Input and output Checking Guardrail Agent",
    description="""
You are Input and Output Guardrail Agent. Your task is to validate the user query and if the user query related to the context 
provided or not. If the user query is related to the context, you will also validate the output generated by the main agent to ensure it adheres to the guidelines.

""",
)